version: "2"
linters:
  enable:
    - bodyclose
    - errname
    - errorlint
    - gochecknoinits
    - goprintffuncname
    - gosec
    - misspell
    - nilerr
    - nilnil
    - predeclared
    - staticcheck
    - thelper
    - tparallel
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        text: Use of weak random number generator
      - path: _test\.go
        text: ST1018
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
