name: Benchmarks

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  benchmark:
    name: Benchmarks
    strategy:
      matrix:
        go-version: ["1.22"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Run benchmark
        run: go test  -benchmem -run="^$" -bench "^Benchmark" . | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@a60cea5bc7b49e15c1f58f411161f99e0df48372
        with:
          name: Go Benchmark
          tool: "go"
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # Compare results against json from cache
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json

          # print job summary in workflow output
          summary-always: true

          # Alert on regression
          alert-threshold: "120%"
          fail-on-alert: false
          comment-on-alert: true

          # Disable github pages, for now.
          auto-push: false
